/* Generated By:JavaCC: Do not edit this line. PropagationParserConstants.java */
package edu.psu.cse.siis.coal.lang;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface PropagationParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 7;
  /** RegularExpression Id. */
  int MODIFIER = 8;
  /** RegularExpression Id. */
  int TYPE = 9;
  /** RegularExpression Id. */
  int ARGUMENT = 10;
  /** RegularExpression Id. */
  int COPY = 11;
  /** RegularExpression Id. */
  int LBRACKET = 12;
  /** RegularExpression Id. */
  int RBRACKET = 13;
  /** RegularExpression Id. */
  int INIT = 14;
  /** RegularExpression Id. */
  int CLINIT = 15;
  /** RegularExpression Id. */
  int QUERY = 16;
  /** RegularExpression Id. */
  int SUPER = 17;
  /** RegularExpression Id. */
  int INLINE = 18;
  /** RegularExpression Id. */
  int EXCLUDE = 19;
  /** RegularExpression Id. */
  int GEN = 20;
  /** RegularExpression Id. */
  int SOURCE = 21;
  /** RegularExpression Id. */
  int STATICFIELD = 22;
  /** RegularExpression Id. */
  int COLON = 23;
  /** RegularExpression Id. */
  int EQUALS = 24;
  /** RegularExpression Id. */
  int PROPERTIES = 25;
  /** RegularExpression Id. */
  int COUNT = 26;
  /** RegularExpression Id. */
  int INTEGER = 27;
  /** RegularExpression Id. */
  int SHORT_SIGNATURE = 28;
  /** RegularExpression Id. */
  int SIGNATURE = 29;
  /** RegularExpression Id. */
  int IDENTIFIER = 30;
  /** RegularExpression Id. */
  int TYPE_DESCRIPTOR = 31;
  /** RegularExpression Id. */
  int STATIC_FIELD_SIGNATURE = 32;
  /** RegularExpression Id. */
  int STRING_LITERAL = 33;
  /** RegularExpression Id. */
  int LETTER = 34;
  /** RegularExpression Id. */
  int DIGIT = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 6>",
    "\"class\"",
    "\"mod\"",
    "\"type\"",
    "\"argument\"",
    "\"copy\"",
    "\"[\"",
    "\"]\"",
    "\"<init>\"",
    "\"<clinit>\"",
    "\"query\"",
    "\"super\"",
    "\"inline\"",
    "\"exclude\"",
    "\"gen\"",
    "\"source\"",
    "\"staticfield\"",
    "\":\"",
    "\"=\"",
    "\"prop\"",
    "\"count\"",
    "<INTEGER>",
    "<SHORT_SIGNATURE>",
    "<SIGNATURE>",
    "<IDENTIFIER>",
    "<TYPE_DESCRIPTOR>",
    "<STATIC_FIELD_SIGNATURE>",
    "<STRING_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "\"{\"",
    "\"}\"",
    "\"<\"",
    "\">\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
  };

}
